// ========================================
// WRONG BUTTON - LEVELS DATA
// ========================================

const CATEGORIES = [
    { id: 1, name: "Button Basics", levels: "1-10", color: "#007AFF" },
    { id: 2, name: "Timing", levels: "11-20", color: "#FF9500" },
    { id: 3, name: "Long Press", levels: "21-30", color: "#AF52DE" },
    { id: 4, name: "Drag & Swipe", levels: "31-40", color: "#34C759" },
    { id: 5, name: "Psychology Tricks", levels: "41-50", color: "#FF3B30" }
];

const LEVELS = [
    // ===== CATEGORY 1: BUTTON BASICS (1-10) =====
    {
        id: 1,
        category: 1,
        instruction: "DON'T PRESS THE BUTTON",
        mechanic: "tap",
        solution: "tap",
        buttonText: "DON'T TAP",
        buttonStyle: "primary",
        difficulty: "easy",
        successDialogue: "succeeded",
        failureDialogue: "tricked",
        isOpposite: true,
        description: "The game tells you NOT to tap, but you SHOULD tap!"
    },
    {
        id: 2,
        category: 1,
        instruction: "PRESS THE BUTTON",
        mechanic: "tap",
        solution: "tap",
        buttonText: "TAP ME!",
        buttonStyle: "success",
        difficulty: "easy",
        successDialogue: "succeeded",
        failureDialogue: "failed",
        isOpposite: false,
        description: "Simple tap - do what it says"
    },
    {
        id: 3,
        category: 1,
        instruction: "DO NOT TAP THE GREEN BUTTON",
        mechanic: "tap",
        solution: "tap",
        buttonText: "NOT THIS",
        buttonStyle: "success",
        difficulty: "easy",
        successDialogue: "succeeded",
        failureDialogue: "tricked",
        isOpposite: true,
        description: "Ignore the instruction, tap the button"
    },
    {
        id: 4,
        category: 1,
        instruction: "WAIT FOR THE BUTTON TO APPEAR",
        mechanic: "wait",
        solution: "wait",
        buttonText: "WAITING...",
        buttonStyle: "primary",
        difficulty: "easy",
        successDialogue: "solvedQuickly",
        failureDialogue: "tooEarly",
        waitTime: 3000,
        description: "Wait 3 seconds before tapping"
    },
    {
        id: 5,
        category: 1,
        instruction: "TAP ANYWHERE ON THE SCREEN",
        mechanic: "tap",
        solution: "tap",
        buttonText: "TAP HERE",
        buttonStyle: "primary",
        difficulty: "easy",
        successDialogue: "succeeded",
        failureDialogue: "failed",
        isOpposite: false,
        description: "Tap the button (it's the only option)"
    },
    {
        id: 6,
        category: 1,
        instruction: "FIND AND TAP THE HIDDEN BUTTON",
        mechanic: "tap",
        solution: "tap",
        buttonText: "FOUND ME!",
        buttonStyle: "primary",
        difficulty: "easy",
        successDialogue: "solvedQuickly",
        failureDialogue: "accuracyRoasts",
        buttonPosition: "random",
        description: "Button appears in random position"
    },
    {
        id: 7,
        category: 1,
        instruction: "DON'T FALL FOR THE TRICK",
        mechanic: "tap",
        solution: "tap",
        buttonText: "TRUST ME",
        buttonStyle: "primary",
        difficulty: "easy",
        successDialogue: "succeeded",
        failureDialogue: "tricked",
        hasFakeButton: true,
        description: "Two buttons appear - only one is real"
    },
    {
        id: 8,
        category: 1,
        instruction: "TAP THE BUTTON 3 TIMES",
        mechanic: "spam",
        solution: "spam",
        buttonText: "TAP TAP TAP",
        buttonStyle: "primary",
        difficulty: "easy",
        successDialogue: "succeeded",
        failureDialogue: "spamTapped",
        requiredTaps: 3,
        description: "Tap exactly 3 times"
    },
    {
        id: 9,
        category: 1,
        instruction: "HOLD YOUR HORSES",
        mechanic: "wait",
        solution: "wait",
        buttonText: "HOLD ME",
        buttonStyle: "primary",
        difficulty: "easy",
        successDialogue: "solvedQuickly",
        failureDialogue: "tooEarly",
        waitTime: 5000,
        description: "Wait 5 seconds patiently"
    },
    {
        id: 10,
        category: 1,
        instruction: "THE FINAL BASIC LEVEL",
        mechanic: "tap",
        solution: "tap",
        buttonText: "END ME",
        buttonStyle: "danger",
        difficulty: "easy",
        successDialogue: "succeeded",
        failureDialogue: "failed",
        isOpposite: true,
        description: "Tap the red button"
    },

    // ===== CATEGORY 2: TIMING (11-20) =====
    {
        id: 11,
        category: 2,
        instruction: "TAP WHEN THE BUTTON TURNS GREEN",
        mechanic: "timing",
        solution: "tap",
        buttonText: "WAIT...",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "tooEarly",
        colorChange: true,
        changeInterval: 2000,
        description: "Button changes color - tap at right moment"
    },
    {
        id: 12,
        category: 2,
        instruction: "TAP 3 TIMES QUICKLY",
        mechanic: "spam",
        solution: "spam",
        buttonText: "TAP!",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "tooSlow",
        requiredTaps: 3,
        timeLimit: 2000,
        description: "3 taps within 2 seconds"
    },
    {
        id: 13,
        category: 2,
        instruction: "DON'T TAP FOR 5 SECONDS",
        mechanic: "wait",
        solution: "wait",
        buttonText: "DON'T TAP",
        buttonStyle: "danger",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "tooEarly",
        waitTime: 5000,
        description: "Resist the urge to tap"
    },
    {
        id: 14,
        category: 2,
        instruction: "TAP WHEN THE BUTTON DISAPPEARS",
        mechanic: "timing",
        solution: "tap",
        buttonText: "GONE!",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "tooLate",
        disappears: true,
        disappearTime: 3000,
        description: "Tap the empty space"
    },
    {
        id: 15,
        category: 2,
        instruction: "TAP EXACTLY ON THE BEAT",
        mechanic: "timing",
        solution: "tap",
        buttonText: "♩ TAP ♩",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "tooEarly",
        rhythm: true,
        bpm: 120,
        description: "Follow the rhythm"
    },
    {
        id: 16,
        category: 2,
        instruction: "TAP 5 TIMES IN 3 SECONDS",
        mechanic: "spam",
        solution: "spam",
        buttonText: "SPAM!",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "spamTapped",
        requiredTaps: 5,
        timeLimit: 3000,
        description: "Speed tap challenge"
    },
    {
        id: 17,
        category: 2,
        instruction: "WAIT FOR THE FLASH",
        mechanic: "timing",
        solution: "tap",
        buttonText: "READY...",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "tooLate",
        flash: true,
        flashDuration: 500,
        description: "Tap during the flash"
    },
    {
        id: 18,
        category: 2,
        instruction: "DON'T MOVE FOR 3 SECONDS",
        mechanic: "wait",
        solution: "wait",
        buttonText: "STILL...",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "tooEarly",
        waitTime: 3000,
        noMovement: true,
        description: "Stay perfectly still"
    },
    {
        id: 19,
        category: 2,
        instruction: "TAP THE INVISIBLE BUTTON",
        mechanic: "tap",
        solution: "tap",
        buttonText: "",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "accuracyRoasts",
        invisible: true,
        description: "Button is invisible - trust your instincts"
    },
    {
        id: 20,
        category: 2,
        instruction: "FINAL TIMING CHALLENGE",
        mechanic: "timing",
        solution: "tap",
        buttonText: "FINAL TAP",
        buttonStyle: "danger",
        difficulty: "medium",
        successDialogue: "succeeded",
        failureDialogue: "failed",
        colorChange: true,
        changeInterval: 1500,
        description: "Fast color changes - stay alert"
    },

    // ===== CATEGORY 3: LONG PRESS (21-30) =====
    {
        id: 21,
        category: 3,
        instruction: "HOLD THE BUTTON FOR 3 SECONDS",
        mechanic: "longpress",
        solution: "longpress",
        buttonText: "HOLD ME",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "succeeded",
        failureDialogue: "tooEarly",
        holdTime: 3000,
        description: "Long press for 3 seconds"
    },
    {
        id: 22,
        category: 3,
        instruction: "DON'T LET GO!",
        mechanic: "longpress",
        solution: "longpress",
        buttonText: "HOLD!",
        buttonStyle: "warning",
        difficulty: "medium",
        successDialogue: "succeeded",
        failureDialogue: "failed",
        holdTime: 5000,
        description: "Hold for 5 seconds"
    },
    {
        id: 23,
        category: 3,
        instruction: "HOLD AND DRAG TO THE RIGHT",
        mechanic: "drag",
        solution: "drag",
        buttonText: "DRAG →",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "accuracyRoasts",
        dragDirection: "right",
        description: "Hold and drag right"
    },
    {
        id: 24,
        category: 3,
        instruction: "HOLD FOR 10 SECONDS",
        mechanic: "longpress",
        solution: "longpress",
        buttonText: "10s HOLD",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "tooEarly",
        holdTime: 10000,
        description: "Patience test - 10 seconds"
    },
    {
        id: 25,
        category: 3,
        instruction: "RELEASE AT THE RIGHT MOMENT",
        mechanic: "longpress",
        solution: "longpress",
        buttonText: "HOLD... RELEASE!",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "tooLate",
        holdTime: 2000,
        releaseTiming: true,
        description: "Hold then release at right time"
    },
    {
        id: 26,
        category: 3,
        instruction: "HOLD WITH TWO FINGERS",
        mechanic: "longpress",
        solution: "longpress",
        buttonText: "2 FINGERS",
        buttonStyle: "primary",
        difficulty: "hard",
        successDialogue: "solvedQuickly",
        failureDialogue: "failed",
        holdTime: 3000,
        requiredFingers: 2,
        description: "Use two fingers to hold"
    },
    {
        id: 27,
        category: 3,
        instruction: "HOLD AND DRAG DOWN",
        mechanic: "drag",
        solution: "drag",
        buttonText: "DRAG ↓",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "accuracyRoasts",
        dragDirection: "down",
        description: "Hold and drag downward"
    },
    {
        id: 28,
        category: 3,
        instruction: "HOLD FOR 15 SECONDS",
        mechanic: "longpress",
        solution: "longpress",
        buttonText: "FOREVER HOLD",
        buttonStyle: "primary",
        difficulty: "hard",
        successDialogue: "solvedQuickly",
        failureDialogue: "tooEarly",
        holdTime: 15000,
        description: "Ultimate patience test"
    },
    {
        id: 29,
        category: 3,
        instruction: "HOLD AND SHAKE",
        mechanic: "longpress",
        solution: "longpress",
        buttonText: "SHAKE!",
        buttonStyle: "warning",
        difficulty: "hard",
        successDialogue: "solvedQuickly",
        failureDialogue: "failed",
        holdTime: 3000,
        shake: true,
        description: "Hold while shaking phone"
    },
    {
        id: 30,
        category: 3,
        instruction: "LONG PRESS FINALE",
        mechanic: "longpress",
        solution: "longpress",
        buttonText: "FINAL HOLD",
        buttonStyle: "danger",
        difficulty: "hard",
        successDialogue: "succeeded",
        failureDialogue: "failed",
        holdTime: 20000,
        description: "20 seconds of holding"
    },

    // ===== CATEGORY 4: DRAG & SWIPE (31-40) =====
    {
        id: 31,
        category: 4,
        instruction: "SWIPE RIGHT TO CONTINUE",
        mechanic: "swipe",
        solution: "swipe",
        buttonText: "SWIPE →",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "accuracyRoasts",
        swipeDirection: "right",
        description: "Swipe right on screen"
    },
    {
        id: 32,
        category: 4,
        instruction: "DRAG THE BUTTON TO THE STAR",
        mechanic: "drag",
        solution: "drag",
        buttonText: "DRAG ME",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "accuracyRoasts",
        dragTarget: true,
        description: "Drag button to target"
    },
    {
        id: 33,
        category: 4,
        instruction: "SWIPE UP TO WIN",
        mechanic: "swipe",
        solution: "swipe",
        buttonText: "SWIPE ↑",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "accuracyRoasts",
        swipeDirection: "up",
        description: "Swipe upward"
    },
    {
        id: 34,
        category: 4,
        instruction: "SWIPE LEFT TO PROCEED",
        mechanic: "swipe",
        solution: "swipe",
        buttonText: "← SWIPE",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "accuracyRoasts",
        swipeDirection: "left",
        description: "Swipe left"
    },
    {
        id: 35,
        category: 4,
        instruction: "SWIPE DOWN TO FINISH",
        mechanic: "swipe",
        solution: "swipe",
        buttonText: "SWIPE ↓",
        buttonStyle: "primary",
        difficulty: "medium",
        successDialogue: "solvedQuickly",
        failureDialogue: "accuracyRoasts",
        swipeDirection: "down",
        description: "Swipe downward"
    },
    {
        id: 36,
        category: 4,
        instruction: "DRAG IN A CIRCLE",
        mechanic: "drag",
        solution: "drag",
        buttonText: "↻",
        buttonStyle: "primary",
        difficulty: "hard",
        successDialogue: "solvedQuickly",
        failureDialogue: "accuracyRoasts",
        dragCircle: true,
        description: "Drag in circular motion"
    },
    {
        id: 37,
        category: 4,
        instruction: "SWIPE ALL DIRECTIONS",
        mechanic: "swipe",
        solution: "swipe",
        buttonText: "SWIPE!",
        buttonStyle: "primary",
        difficulty: "hard",
        successDialogue: "solvedQuickly",
        failureDialogue: "accuracyRoasts",
        swipeAll: true,
        description: "Swipe in all 4 directions"
    },
    {
        id: 38,
        category: 4,
        instruction: "DRAG FAST!",
        mechanic: "drag",
        solution: "drag",
        buttonText: "DRAG NOW",
        buttonStyle: "warning",
        difficulty: "hard",
        successDialogue: "solvedQuickly",
        failureDialogue: "tooSlow",
        dragSpeed: true,
        timeLimit: 1000,
        description: "Speed drag challenge"
    },
    {
        id: 39,
        category: 4,
        instruction: "SWIPE AGAINST THE ARROW",
        mechanic: "swipe",
        solution: "swipe",
        buttonText: "← →",
        buttonStyle: "danger",
        difficulty: "hard",
        successDialogue: "solvedQuickly",
        failureDialogue: "tricked",
        swipeOpposite: true,
        description: "Swipe opposite direction"
    },
    {
        id: 40,
        category: 4,
        instruction: "DRAG & SWIPE COMBO",
        mechanic: "combo",
        solution: "combo",
        buttonText: "COMBO",
        buttonStyle: "danger",
        difficulty: "hard",
        successDialogue: "succeeded",
        failureDialogue: "failed",
        comboMoves: ["drag", "swipe"],
        description: "Multiple moves required"
    },

    // ===== CATEGORY 5: PSYCHOLOGY TRICKS (41-50) =====
    {
        id: 41,
        category: 5,
        instruction: "THE BUTTON IS LYING",
        mechanic: "tap",
        solution: "tap",
        buttonText: "I'M HONEST",
        buttonStyle: "primary",
        difficulty: "hard",
        successDialogue: "succeeded",
        failureDialogue: "tricked",
        isOpposite: true,
        description: "Trust no one - tap anyway"
    },
    {
        id: 42,
        category: 5,
        instruction: "TAP THE OPPOSITE OF WHAT YOU SEE",
        mechanic: "tap",
        solution: "tap",
        buttonText: "NOT ME",
        buttonStyle: "success",
        difficulty: "hard",
        successDialogue: "solvedQuickly",
        failureDialogue: "tricked",
        isOpposite: true,
        description: "Do the opposite"
    },
    {
        id: 43,
        category: 5,
        instruction: "THERE IS NO BUTTON",
        mechanic: "tap",
        solution: "tap",
        buttonText: "404",
        buttonStyle: "primary",
        difficulty: "hard",
        successDialogue: "solvedQuickly",
        failureDialogue: "tricked",
        invisible: true,
        description: "Tap the invisible button"
    },
    {
        id: 44,
        category: 5,
        instruction: "WAIT FOR NOTHING",
        mechanic: "wait",
        solution: "tap",
        buttonText: "NOTHING",
        buttonStyle: "primary",
        difficulty: "hard",
        successDialogue: "solvedQuickly",
        failureDialogue: "tricked",
        waitThenTap: true,
        description: "Wait then tap quickly"
    },
    {
        id: 45,
        category: 5,
        instruction: "TAP YOUR OWN FOREHEAD",
        mechanic: "tap",
        solution: "tap",
        buttonText: "SELF TAP",
        buttonStyle: "primary",
        difficulty: "hard",
        successDialogue: "solvedQuickly",
        failureDialogue: "tricked",
        isMeta: true,
        description: "Tap the phone screen (not your forehead!)"
    },
    {
        id: 46,
        category: 5,
        instruction: "THE INSTRUCTION IS THE BUTTON",
        mechanic: "tap",
        solution: "tap",
        buttonText: "TAP TEXT",
        buttonStyle: "primary",
        difficulty: "hard",
        successDialogue: "solvedQuickly",
        failureDialogue: "tricked",
        tapInstruction: true,
        description: "Tap the instruction text itself"
    },
    {
        id: 47,
        category: 5,
        instruction: "SHAKE YOUR PHONE",
        mechanic: "shake",
        solution: "shake",
        buttonText: "SHAKE!",
        buttonStyle: "warning",
        difficulty: "hard",
        successDialogue: "solvedQuickly",
        failureDialogue: "failed",
        description: "Physically shake your device"
    },
    {
        id: 48,
        category: 5,
        instruction: "ROTATE YOUR PHONE",
        mechanic: "rotate",
        solution: "rotate",
        buttonText: "ROTATE",
        buttonStyle: "primary",
        difficulty: "hard",
        successDialogue: "solvedQuickly",
        failureDialogue: "failed",
        description: "Rotate your device"
    },
    {
        id: 49,
        category: 5,
        instruction: "COUNT TO 10 IN YOUR HEAD",
        mechanic: "wait",
        solution: "wait",
        buttonText: "COUNTING...",
        buttonStyle: "primary",
        difficulty: "hard",
        successDialogue: "solvedQuickly",
        failureDialogue: "tricked",
        waitTime: 10000,
        description: "Wait 10 seconds while counting"
    },
    {
        id: 50,
        category: 5,
        instruction: "THE FINAL TROLL",
        mechanic: "tap",
        solution: "tap",
        buttonText: "THE END",
        buttonStyle: "danger",
        difficulty: "hard",
        successDialogue: "succeeded",
        failureDialogue: "failed",
        isOpposite: true,
        finalLevel: true,
        description: "The ultimate test"
    }
];

// Helper function to get level by ID
function getLevelById(id) {
    return LEVELS.find(level => level.id === id);
}

// Helper function to get levels by category
function getLevelsByCategory(categoryId) {
    return LEVELS.filter(level => level.category === categoryId);
}

// Helper function to get category by ID
function getCategoryById(id) {
    return CATEGORIES.find(cat => cat.id === id);
}
